modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "litematica_printer_forge"
version = "${version}"
displayName = "Litematica Printer Forge"
updateJSONURL = "https://github.com/jxmm52547/litematica-printer"
displayURL = "https://www.github.com/jxmm52547/litematica-printer"
logoFile = "assets/litematica_printer_forge/icon.png"
authors = "jxmm"
description = '''Litematica Printer for Forge'''

[[mixins]]
config = "litematica_printer_forge.mixins.json"

[[dependencies."litematica_printer_forge"]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."litematica_printer_forge"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies."litematica_printer_forge"]]
modId = "mafglib"
mandatory = true
versionRange = "[0.1.14-mc1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."litematica_printer_forge"]]
modId = "forgematica"
mandatory = true
versionRange = "[0.1.10-mc1.19.2,)"
ordering = "NONE"
side = "BOTH"
